In [1]:
import numpy as np
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [3]:
b=np.array([[1,3,5],[2,4,6]])
print(b)

[[1 3 5]
 [2 4 6]]


In [4]:
a.dtype

dtype('int32')

In [5]:
a.ndim

1

In [6]:
b.ndim

2

In [7]:
a.shape

(6,)

In [8]:
b.shape

(2, 3)

In [9]:
a.itemsize

4

In [10]:
a.nbytes

24

In [11]:
x=np.array([0,1,2,3,4,5,6,7,8,9])
x[1:7:2]


array([1, 3, 5])

In [12]:
b[0][1]

3

In [13]:
b[1][6]

IndexError: index 6 is out of bounds for axis 0 with size 3

In [14]:
print(b)

[[1 3 5]
 [2 4 6]]


In [15]:
b.reshape(3,2)

array([[1, 3],
       [5, 2],
       [4, 6]])

In [16]:
print(b)

[[1 3 5]
 [2 4 6]]


In [17]:
b.swapaxes(0,1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
c=b.flatten()
c

array([1, 3, 5, 2, 4, 6])

In [20]:
np.sort(c)

array([1, 2, 3, 4, 5, 6])

In [21]:
data=np.arange(0,1000)
print(data.dtype)

int32


In [22]:
print(data.nbytes)

4000


In [23]:
data=np.arange(0,1000,dtype='int8')
print(data.dtype)

int8


In [24]:
print(data.nbytes)

1000
