In [1]:
!pip install numpy

In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
b=np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

In [4]:
c=np.linspace(1,10,5)
c

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [6]:
d=np.zeros((2,2))
d

array([[0., 0.],
       [0., 0.]])

In [7]:
e=np.ones((3,3))
e

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
f=np.full((5,),7)
f

array([7, 7, 7, 7, 7])

In [10]:
g=np.full((5,2),9)
g

array([[9, 9],
       [9, 9],
       [9, 9],
       [9, 9],
       [9, 9]])

In [14]:
h=np.fromstring('5 10 15 20 25', dtype=np.int,sep=' ')
h

C:\Users\Dell\AppData\Local\Temp\ipykernel_6496\2647527673.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  h=np.fromstring('5 10 15 20 25', dtype=np.int,sep=' ')


array([ 5, 10, 15, 20, 25])

In [13]:
h.dtype

dtype('int32')

In [15]:
np.around([0.37,1.64,1.5,1.49])

array([0., 2., 2., 1.])

In [16]:
np.around([0.37,1.64,1.5,1.49], decimals=1)

array([0.4, 1.6, 1.5, 1.5])

In [17]:
a

array([1, 2, 3, 4, 5])

In [18]:
a.sum()

15

In [20]:
a=np.array([[1,2,3],[4,5,6]])
a.sum()

21

In [21]:
a.sum(axis=0)

array([5, 7, 9])

In [22]:
a.sum(axis=1)

array([ 6, 15])

In [23]:
price=np.array([350,500,400,250,150])
print('min value:', price.min())

min value 150


In [25]:
price=np.array([350,500,400,250,150])
print('min value:', price.min())
print('max value:', price.max())
print('mean value:',price.mean())
print('var value:',price.var())
print('std value:', price.std())

min value: 150
max value: 500
mean value: 330.0
var value: 14600.0
std value: 120.83045973594572


In [26]:
print(price)

[350 500 400 250 150]


In [27]:
price.argmin()

4

In [28]:
price.argmax()

1

In [3]:
textData=np.loadtxt('data.txt', skiprows=1, delimiter=',', dtype=np.int32)
textData

array([[ 1,  2,  3,  4,  5],
       [ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10],
       [ 2,  3,  5,  7, 11],
       [ 2,  4,  8, 16, 32]])

In [5]:
textData=np.genfromtxt('data.txt', skip_header=1, delimiter=',', dtype=np.int32)
textData

array([[ 1,  2,  3,  4,  5],
       [ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10],
       [ 2,  3,  5,  7, 11],
       [ 2,  4,  8, 16, 32]])

In [6]:
multipleFive=textData*5
multipleFive

array([[  5,  10,  15,  20,  25],
       [  5,  15,  25,  35,  45],
       [ 10,  20,  30,  40,  50],
       [ 10,  15,  25,  35,  55],
       [ 10,  20,  40,  80, 160]])

In [9]:
np.savetxt('new_data.txt', multipleFive,delimiter=',', fmt='%d',header='v1,v2,v3,v4,v5', comments='')
